### ISSUE TITLE
Donation link not working

### ISSUE THREAD

**Issue by CryptoHobbyist** [sui77/stellar-candyman#1]
I have been using your (I think) TOML checker http://www.steiiar-cuba.digital/ and tried to follow the link to donate but it is not working. https://lumenthropy.com/.
I hope you are still working on that project and see this note. I'll try again in the future

**Comment by sui77** [comment]
Thanks for the heads up. The lumentrophy project was a directory of charities that accepted stellar lumens. The site was closed and so I've removed the link. If you feel like donating, just pick a charity of your choice :)
